## In this notebook we are going to learn some of the most fundamental concepts of tensors using tensorflow

* More specifically, we are going to cover:
1. Introduction to tensors
1. Getting information from tensors
1. Manipulating Tensors
1. Tensors and Numpy
1. Using @tf.function (a way to speed up your regular tensor functions)
1. Using GPU's with tensor flow(or TPU)

### Introduction To Tensors

##### Creating tensors with tf.constant

In [1]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__) # this will give the version of tensor flow i am using

2.10.0


In [2]:
# create tensors with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking the dimension of scalar
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,54])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 54])>

In [5]:
# check the dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[10,4],[12,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [12, 40]])>

In [7]:
# checking dimension of matrix
matrix.ndim

2

In [8]:
# creating a 3-d martix with tf.constant()
matrix_3d = tf.constant([[[10,12],[31,22]],[[12,43],[56,22]]])
matrix_3d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[10, 12],
        [31, 22]],

       [[12, 43],
        [56, 22]]])>

In [9]:
# checking dimension of 3d matrix

matrix_3d.ndim

3

In [10]:
# defining datatype(dtype) using tf.float

another_matrix=tf.constant([[12.2,13.],[82.,55.],[71.,25.]],dtype=tf.float16) #dot specify float 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[12.2, 13. ],
       [82. , 55. ],
       [71. , 25. ]], dtype=float16)>

In [11]:
# checking Dimensions of another_matrix
another_matrix.ndim

2

##### Creating tensors with tf.variable

In [12]:
changeable_tensor=tf.Variable([10,2]) # 'V' is capital here 
unchangeable_tensor = tf.constant([10,2])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2])>)

In [13]:
#lets try and change one of the elements in our changable tensor

changeable_tensor[0].assign(7)
changeable_tensor

# we cannot assign values to tensor created using tf.constant

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2])>

##### Creating random tensor 

In [14]:
# random tensors are tensors of some arbitary size containg random numbers

# creating two random (but same seed) tensors

random_1=tf.random.Generator.from_seed(42) # set seed for reproducability
random_1 = random_1.normal(shape=(3,2)) # '.normal' means it outputs random values from normal distribution

random_2=tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

rand_1=tf.random.Generator.from_seed(42).normal(shape=(3,2))

# are rand_1,random_1 and random_2 equal?
random_1,random_2, random_1==random_2,rand_1== random_1




(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
random_01= tf.random.normal([2,2],mean=2,stddev=1.0,dtype=tf.float16,seed=42)
random_02= tf.random.normal([2,2],mean=2,stddev=1.0,dtype=tf.float16,seed=42)

#are random_01 and random_02 equal?
random_01,random_02, random_01==random_02

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1.719, 1.862],
        [1.324, 2.025]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[-0.3457,  1.886 ],
        [ 3.404 ,  1.941 ]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False]])>)

In [16]:
# if we dont specify seed then they wont be equal

random_3 = tf.random.normal(shape=(3,2))

random_4 = tf.random.normal(shape=(3,2))

# are random_3 and random_4 equal?

random_3,random_4,random_3==random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.3855714 , -1.1219963 ],
        [ 0.97922647,  1.503597  ],
        [ 0.25781143, -0.1718457 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.5337398 ,  0.8289964 ],
        [-0.6213994 ,  0.04132111],
        [-0.817253  , -1.0308022 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [17]:
# generating random tensors using different distributions

random_5 = tf.random.uniform(shape=(3,4,2)) # Outputs pseudorandom values from a normal distribution

random_6 = tf.random.gamma(shape=(2,1,4),alpha=1,beta=1,dtype=tf.float16,seed=14) # Draws shape samples from each of the given Gamma distribution(s)

random_5, random_6

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.38416505, 0.18462455],
         [0.434039  , 0.42350757],
         [0.17831218, 0.93320215],
         [0.9753387 , 0.7481096 ]],
 
        [[0.16226304, 0.30822468],
         [0.39582026, 0.6223463 ],
         [0.70495236, 0.06336379],
         [0.9136727 , 0.8175832 ]],
 
        [[0.2779596 , 0.4193226 ],
         [0.3116349 , 0.8414055 ],
         [0.8192711 , 0.8321687 ],
         [0.2627313 , 0.41733944]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1, 4), dtype=float16, numpy=
 array([[[8.350e-01, 1.847e-01, 1.210e+00, 1.835e+00]],
 
        [[5.059e+00, 3.538e-03, 6.519e-01, 2.007e-01]]], dtype=float16)>)

##### Shuffling the order of elements in tensor

In [18]:
#shuffle a tensor (so that our inherent order doesnot effect the learning)

not_shuffled_1 = tf.constant([[1,2],[1,7],[3,5]])
not_shuffled_2 = tf.constant([[4,9],[8,8],[11,13]])
not_shuffled_1, not_shuffled_1.ndim,not_shuffled_2,not_shuffled_2.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [1, 7],
        [3, 5]])>,
 2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 4,  9],
        [ 8,  8],
        [11, 13]])>,
 2)

In [19]:
# shuffling our not shuffled tensor
tf.random.set_seed(10)
tf.random.shuffle(not_shuffled_1,seed=3) # will shuffle along the first dimension of tensor

#if global seed and local seed both same then tensor wont change
#if global seed changes but local seed remains same then tensor will change
#if global seed remains same but local seed changes then tensor will change
#if both will change then tensor will change.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [1, 7],
       [1, 2]])>

In [20]:
# effect of global seed remains throughout the cell in jupyter notebook

tf.random.set_seed(10)
a = tf.random.shuffle(not_shuffled_1,seed=3)
b = tf.random.shuffle(not_shuffled_2,seed=3)

a,b

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [1, 7],
        [1, 2]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 8,  8],
        [ 4,  9],
        [11, 13]])>)

##### Turn numpy arrays into tensorflow tensors
* Main difference between numpy arrays and tensorflow tensors is that tensors can be run on gpu(much faster for numerical computing)

In [21]:
# Turning numpy arrays into tensors
import numpy as np

# X = tf.constant(some_matrix), Capital for matrix and tensors
# y = tf.constant(some_vector), Non capital for vector and scalar

numpy_A = np.arange(1,25,dtype=np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [23]:
B = tf.constant(numpy_A,shape=(3,8))
C =tf.constant(numpy_A,shape=(2,3,4))
B,C

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

In [24]:
# creating tensors with all ones in it
tf.ones(shape=(2,2,2))

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [25]:
# creating tensors with all zeroes in it
tf.zeros(shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

### Getting information from tensors
* Shape
* Rank
* Axis or Dimension
* Size

In [26]:
# create a rank 4 tensor(4 Dimensions)

rank_4_tensor= tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# getiing different attributes of our tensor

print('Datatype of every element:',rank_4_tensor.dtype)
print('Number of dimensions(rank):',rank_4_tensor.ndim)
print('Shape of tensor:',rank_4_tensor.shape)
print('Elements along the zero axis :',rank_4_tensor.shape[0])
print('Elements along the last axis :',rank_4_tensor.shape[-1])
print('Elements along the zero axis :',rank_4_tensor.shape[-4])
print('total number of elements in our tensor:',tf.size(rank_4_tensor))
print('total number of elements in our tensor',tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the zero axis : 2
Elements along the last axis : 5
Elements along the zero axis : 2
total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor 120


##### Indexing tensors
* tensors can be indexed just like python list.

In [30]:
some_list= [1,2,3,4,5]
some_list[1:4],some_list[:3]

([2, 3, 4], [1, 2, 3])

In [31]:
new_rank_4_tensor=tf.range(1,121)
new_rank_4_tensor=tf.reshape(new_rank_4_tensor,[2,3,4,5])
new_rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [32]:
# get the first element from each dimension except the last one
new_rank_4_tensor[0:1,0:1,0:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [33]:
new_rank_4_tensor[:1,:1,:,0:1],new_rank_4_tensor[0:1,:,0:1,0:1],new_rank_4_tensor[:,:1,:1,:1]

(<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
 array([[[[ 1],
          [ 6],
          [11],
          [16]]]])>,
 <tf.Tensor: shape=(1, 3, 1, 1), dtype=int32, numpy=
 array([[[[ 1]],
 
         [[21]],
 
         [[41]]]])>,
 <tf.Tensor: shape=(2, 1, 1, 1), dtype=int32, numpy=
 array([[[[ 1]]],
 
 
        [[[61]]]])>)

In [34]:
new_rank_4_tensor[:1,:1,:1,:].shape,new_rank_4_tensor[:1,:1,:,:1].shape,new_rank_4_tensor[:1,:,:1,:1].shape,new_rank_4_tensor[:,:1,:1,:1].shape

(TensorShape([1, 1, 1, 5]),
 TensorShape([1, 1, 4, 1]),
 TensorShape([1, 3, 1, 1]),
 TensorShape([2, 1, 1, 1]))

In [35]:
#create a rank 2 tensor
rank_2_tensor= tf.constant([[10,8,5],[8,3,9]])
rank_2_tensor,rank_2_tensor.ndim,rank_2_tensor.shape

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  8,  5],
        [ 8,  3,  9]])>,
 2,
 TensorShape([2, 3]))

In [36]:
#getting last elemet of each row of our rank 2 tensor

rank_2_tensor[:,2:3],rank_2_tensor[:,-1]

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[5],
        [9]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 9])>)

In [37]:
# Adding extra dimension to our rank 2 tensor at the end 
rank_3_tensor_1=rank_2_tensor[...,tf.newaxis] #equivalent to writing rank_3_tensor_1=rank_2_tensor[0:2,0:3,tf.newaxis]
rank_3_tensor_1

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 8],
        [ 5]],

       [[ 8],
        [ 3],
        [ 9]]])>

In [38]:
# Adding extra dimension to our rank 2 tensor at the start
rank_3_tensor_2=rank_2_tensor[tf.newaxis,...] #equivalent to writing rank_3_tensor_2=rank_2_tensor[tf.newaxis,0:2,0:3]
rank_3_tensor_2

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[10,  8,  5],
        [ 8,  3,  9]]])>

In [45]:
# Adding extra dimension to our rank 2 tensor in the middle
rank_3_tensor_3=rank_2_tensor[:,tf.newaxis,:]
rank_3_tensor_3

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[10,  8,  5]],

       [[ 8,  3,  9]]])>

In [44]:
# Adding more than one extra dimension to our rank 2 tensor
high_rank_tensor=rank_2_tensor[:,tf.newaxis,tf.newaxis,:,tf.newaxis]
high_rank_tensor,high_rank_tensor.shape,high_rank_tensor.ndim

(<tf.Tensor: shape=(2, 1, 1, 3, 1), dtype=int32, numpy=
 array([[[[[10],
           [ 8],
           [ 5]]]],
 
 
 
        [[[[ 8],
           [ 3],
           [ 9]]]]])>,
 TensorShape([2, 1, 1, 3, 1]),
 5)

In [41]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # here -1 axis means expainsion at final axis

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 8],
        [ 5]],

       [[ 8],
        [ 3],
        [ 9]]])>

In [42]:
tf.expand_dims(rank_2_tensor,axis=-1).shape,tf.expand_dims(rank_2_tensor,axis=-2).shape,tf.expand_dims(rank_2_tensor,axis=-3).shape

(TensorShape([2, 3, 1]), TensorShape([2, 1, 3]), TensorShape([1, 2, 3]))

In [43]:
tf.expand_dims(rank_2_tensor,axis=0).shape,tf.expand_dims(rank_2_tensor,axis=1).shape,tf.expand_dims(rank_2_tensor,axis=2).shape

(TensorShape([1, 2, 3]), TensorShape([2, 1, 3]), TensorShape([2, 3, 1]))

### Manipulating tensors (tensor operations)

**Basic Operation**

+,-,*,/

In [79]:
# You can add values to a tensor using addition
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [80]:
#multiplication
tensor*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]])>

In [81]:
#subtractin
tensor-3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 4],
       [0, 1]])>

In [82]:
#division
tensor/13

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.76923077, 0.53846154],
       [0.23076923, 0.30769231]])>

In [83]:
# We can use tensorflow builtin functions also
tf.multiply(tensor,10),tf.add(tensor,5),tf.subtract(tensor,4),tf.divide(tensor,5)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 12],
        [ 8,  9]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  3],
        [-1,  0]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[2. , 1.4],
        [0.6, 0.8]])>)

**Matrix Multiplication** 

In [87]:
#matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor),tensor@tensor #both can be used

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[100,  70],
          [ 30,  40]],
 
         [[ 70,  49],
          [ 21,  28]]],
 
 
        [[[ 30,  21],
          [  9,  12]],
 
         [[ 40,  28],
          [ 12,  16]]]])>)

In [64]:
#element wise multiplication of tensor
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [70]:
tensor1=tf.constant([[12,3,5],[8,2,6],[3,3,2]])
tensor2=tf.constant([[1,3],[2,6],[8,1]])
tensor1@tensor2,tf.matmul(tensor1,tensor2)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[58, 59],
        [60, 42],
        [25, 29]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[58, 59],
        [60, 42],
        [25, 29]])>)

In [71]:
#changing shape of tensor
print(tensor2)
tensor2=tf.reshape(tensor2,shape=(2,3))
tensor2

tf.Tensor(
[[1 3]
 [2 6]
 [8 1]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 2],
       [6, 8, 1]])>

In [76]:
tensor3=tf.constant([[1,2],[3,9],[7,2]])
tensor4=tf.constant([[1,3],[4,4],[3,9]])

print(tf.matmul(tf.reshape(tensor3,shape=(2,3)),tensor4))
print(tf.matmul(tensor3,tf.reshape(tensor4,shape=(2,3))))

tf.Tensor(
[[18 38]
 [43 73]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 9  9 22]
 [39 36 93]
 [15 27 46]], shape=(3, 3), dtype=int32)


In [77]:
#transpose flips the axises, whereas reshape shuffels the tensor around into the shape that we want
print(tf.matmul(tf.transpose(tensor3),tensor4))
print(tf.matmul(tensor3,tf.transpose(tensor4)))

tf.Tensor(
[[34 78]
 [44 60]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 12 21]
 [30 48 90]
 [13 36 39]], shape=(3, 3), dtype=int32)


In [94]:
# Another function for matrix multiplication
tf.tensordot(tensor,tensor,axes=0),tf.tensordot(tensor,tensor,axes=1)

#When a and b are matrices (order 2), the case axes=1 is equivalent to matrix multiplication.

#When a and b are matrices (order 2), the case axes=0 gives the outer product, a tensor of order 4.



(<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[100,  70],
          [ 30,  40]],
 
         [[ 70,  49],
          [ 21,  28]]],
 
 
        [[[ 30,  21],
          [  9,  12]],
 
         [[ 40,  28],
          [ 12,  16]]]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>)

**Change the datatype of tensor**

In [95]:
# create a new tensor with default datatype(float32)
b=tf.constant([1.7,7.4])
c=tf.constant([12,10])
b.dtype,c.dtype

(tf.float32, tf.int32)

In [96]:
b=tf.cast(b,dtype=tf.float16)
c=tf.cast(c,dtype=tf.int16)
b.dtype,c.dtype

(tf.float16, tf.int16)

In [97]:
d=tf.cast(c,dtype=tf.float16)
d

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([12., 10.], dtype=float16)>

**Aggregating Tensors**

*aggregating tensors = condensing them from multiple value down to a smaller amount of values*

In [99]:
#getting the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [100]:
#gets the absolute value
tf.abs(D) #each elements will return absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

lets go through the following forms of aggregation
* get the minimum
* get the maximum
* get the mean of tensor
* get the sum of tensor

In [105]:
# creating a random tensor with values between 0 and 100 and of size 50
E= tf.constant(np.random.randint(0,100,size=50))
E,tf.size(E).numpy(),E.shape,E.ndim

(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([99, 81, 68, 28, 42, 91, 63, 30, 50, 29, 75, 73, 72, 20, 15, 49,  6,
        85, 60, 65, 16,  9, 14, 93, 48, 21, 13, 72, 26, 44, 84, 34, 26, 17,
        53,  4, 80, 91, 40, 19, 62, 42, 78, 74, 26, 91, 18, 24, 66, 98])>,
 50,
 TensorShape([50]),
 1)

In [108]:
#finding minimum of tensor
tf.reduce_min(E),tf.reduce_min(E).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=4>, 4)

In [109]:
#finding maximum of tensor
tf.reduce_max(E),tf.reduce_max(E).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=99>, 99)

In [110]:
#finding mean of tensor
tf.reduce_mean(E),tf.reduce_mean(E).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=49>, 49)

In [111]:
#finding sum of tensor
tf.reduce_sum(E),tf.reduce_sum(E).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=2484>, 2484)

In [114]:
# find the variance of our tensor
import tensorflow_probability as tfp
tfp.stats.variance(E),tfp.stats.variance(E).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=808>, 808)

In [115]:
# find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)) # only works for float data type

<tf.Tensor: shape=(), dtype=float32, numpy=28.422132>

In [116]:
# find the variance of our tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=807.8176>,)

**Find positional maximum and minimum of tensor**

In [120]:
# create a new tensor for findinf positional maximum and minimum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [124]:
#find the positional maximum
tf.argmax(F,axis=0).numpy(),F[tf.argmax(F,axis=0)]

(42, <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [126]:
assert tf.reduce_max(F) == F[tf.argmax(F,axis=0)]
#assert will throw error if they both are not equal

In [127]:
tf.reduce_max(F) == F[tf.argmax(F,axis=0)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [129]:
tf.argmin(F),F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

**Squeezing the tensor**
(removing all single dimensions)

In [130]:
# create a tensor to get started
G=tf.constant(tf.random.uniform(shape=[1,1,1,1,50]))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [133]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [134]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

**One hot encoding tensors**

In [144]:
#create a list of indices
some_list=[0,1,2,3] #could be red, green, blue, purple

#one hot encode our list of indices
tf.one_hot(some_list,depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [145]:
some_list=[[0,1,2,3],[4,5,6,7]]

tf.one_hot(some_list,depth=8)


<tf.Tensor: shape=(2, 4, 8), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]]], dtype=float32)>

In [141]:
#specify custom values for one hot encoding
tf.one_hot(some_list,depth=4, on_value='on',off_value='off')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'on']], dtype=object)>

**Squaring, Log, Square root**

In [146]:
#create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [147]:
#Squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [151]:
tf.sqrt(tf.cast(H,dtype=tf.float16)) #cant use integer values

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [152]:
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and Numpy
TensorFlow interacts beautifully with NumPy arrays

In [153]:
# converts a tensor driectly from a numpy array
J=tf.constant(np.array([3,4,5,6,7,8,9]))
J

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([3, 4, 5, 6, 7, 8, 9])>

In [154]:
# convert our tensor back to numpy array
np.array(J)

array([3, 4, 5, 6, 7, 8, 9])

In [155]:
# convert our tensor J to numpy array
J.numpy()

array([3, 4, 5, 6, 7, 8, 9])

In [157]:
J=tf.constant([3.])
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [160]:
J.numpy(),J.numpy()[0]

(array([3.], dtype=float32), 3.0)

In [163]:
#default types of each are slightly different
numpy_J = tf.constant(np.array([1.,2.,3.,4.,5.,6.]))
tensor_J= tf.constant([12.,3.,5.,2.,4.,6.])

#check the datatypes of each
numpy_J.dtype,tensor_J.dtype


(tf.float64, tf.float32)

### Finding access to Gpu

In [165]:
tf.config.list_physical_devices("GPU")

[]